- defaultTab: nodes
  description: |-
    This is an example when Ruleset is used as Workflow Strategy - with Error Handler and Script File.
    This will include:
     - 1 step in parallel of the remaining workflow
     - 1 job reference step (just running another script)
     - 1 local script step running a script saved in the node
     - 1 error handler to use the previous step state as a condition
     - 2 steps running based in the step state from the previous step. These steps are also reading a Global Variable value.
     - 1 step halting the execution in case of an error. This step also runs based in a job option value.
     - 1 final step to wrap-up the workflow (which only runs after specific steps)
  executionEnabled: true
  group: RBA Features/Ruleset
  id: 10c57ba1-721a-46bf-a4d8-d363db4a1468
  loglevel: INFO
  name: Ruleset example - Application upgrade
  nodeFilterEditable: false
  options:
  - label: File Path
    name: filepath
    value: /opt/apps/runner/test-script.sh
  - enforced: true
    label: Mode
    name: mode
    value: KeepGoing
    values:
    - HaltExecution
    - KeepGoing
    valuesListDelimiter: ','
  - enforced: true
    label: Step 3 result
    name: step-3-result
    value: '0'
    values:
    - '0'
    - '1'
    valuesListDelimiter: ','
  plugins:
    ExecutionLifecycle: {}
  runnerSelector:
    filter: LINUX
    runnerFilterMode: TAGS
    runnerFilterType: TAG_FILTER_AND
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - description: Announce upgrade on MS Teams
      script: |-
        echo "Starting step #1"

        sleep 20s

        echo "Completing step #1"
    - description: Push upgrade packages to the server
      jobref:
        args: -filepath ${option.filepath}
        failOnDisable: true
        group: Ruleset
        name: Referenced job
        useName: 'true'
        uuid: 0ad8669a-2dc4-4e9b-8797-12b03887438f
    - description: Start upgrade
      errorhandler:
        configuration:
          export: step-result
          group: export
          value: NOK
        keepgoingOnSuccess: true
        nodeStep: false
        type: export-var
      exec: ${option.filepath} ${option.step-3-result}
    - description: OK
      script: |-
        echo "Step #4 - OK case"
        echo "Step 3 Global var: @export.step-result@"

        echo "step variable - ${3:exec.exitCode*}"

        exit 0
    - description: NOK
      script: |-
        echo "Step #4 - Not OK case"
        echo "Step 3 result via logfilter: @export.step-result@"

        exit 0
    - configuration:
        debugOnly: 'false'
      description: Final step - wrap up
      nodeStep: false
      type: log-data-step
    - configuration:
        fail: 'true'
        halt: 'true'
      description: Halt execution
      nodeStep: false
      type: flow-control
    keepgoing: false
    pluginConfig:
      WorkflowStrategy:
        ruleset:
          rules: |-
            # Autogenerated Directives
            [1] run-at-start
            [2] run-at-start
            [3] run-after:2
            [4] run-after:3
            [5] run-after:3
            [6] run-after:1,4,7
            [7] run-after:5

            # Autogenerated Conditions
            [4] if:export.step-result!=NOK
            [5] if:export.step-result==NOK
            [7] if:export.step-result==NOK if:option.mode==HaltExecution
    strategy: ruleset
  tags: ruleset
  user: admin
  uuid: 10c57ba1-721a-46bf-a4d8-d363db4a1468

